<a href="https://colab.research.google.com/github/Kirtanaaa/MLTOOLS/blob/main/numpyy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a1=[1,2,3]
np.array(a1)

array([1, 2, 3])

In [7]:
a2=[1,2,'hello',"world"]
np.array(a2)

array(['1', '2', 'hello', 'world'], dtype='<U21')

In [11]:
a3=np.zeros(7)
a4=np.ones(7)
print(a3)
print(a4)

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]


In [13]:
a3[3]=61
print(a3)

[ 0.  0.  0. 61.  0.  0.  0.]


In [14]:
a5=np.zeros(7, int)
a4=np.ones(7)
print(a5)
print(a4)

[0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1.]


In [16]:
a5.dtype

dtype('int64')

In [17]:
a4.dtype

dtype('float64')

In [20]:
np.zeros((3,3),int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
b=np.ones((3,3,3),int)
print(b)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [24]:
b[0][1]

array([1, 1, 1])

In [27]:
b[0][1][2]

1

In [32]:
a5=np.zeros(5,int)
print(a5)
print(a5[2:5])

[0 0 0 0 0]
[0 0 0]


In [34]:
tda=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(tda)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
print(tda[0][1])
print(tda[2])
print(tda[:,2]) #tda[rows,cols], : means all rows are considered
print(tda[1:3,0])
print(tda[0:2,1:3])

2
[7 8 9]
[3 6 9]
[4 7]
[[2 3]
 [5 6]]


In [40]:
import math as m

In [46]:
x = [1,2,3]
y = [4,5,6]
print(x+y)

[1, 2, 3, 4, 5, 6]


In [47]:
print(x+10)

TypeError: ignored

In [44]:
x1=np.array([1,2,3])
y1=np.array([4,5,6])
print(x1+y1)

[5 7 9]


In [48]:
print(x1+10)

[11 12 13]


In [49]:
print(y1.mean())
print(x1.sum())

5.0
6


In [51]:
val=((y1-x1)**2).sum()
print(val)

27


In [52]:
m.sqrt(val)

5.196152422706632

In [55]:
p=np.array([10,20,30,40])
v1=((p-p.mean())**2).sum()
print(v1)
m.sqrt(v1)

500.0


22.360679774997898

In [56]:
print(x1.dot(y1))

32
